title: "Atlas Language Institute"
about_text: >
  At Atlas Language Institute, we are passionate about helping learners unlock new opportunities through language mastery. 
  Our courses are designed for both beginners and advanced students, covering English, French, Spanish, Arabic, and German. 
  We offer flexible online courses that allow students to learn at their own pace, from anywhere in the world. 
  Our experienced instructors provide personalized guidance to ensure each student achieves their goals. 
  Our alumni consistently report high satisfaction, citing improved communication skills, increased confidence, and real-world language application. 
whatsapp_number: "+96171277970"

plugins:
  - jekyll-sitemap

collections:
  courses:
